[package]
name = "simpile-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.13.1"
simpile = { version = "0.1.0", path = "..", features = ["std", "paranoid"] }
